version: 2
jobs:
  build:
    docker:
      - image: docker:18.05.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Build image
          command: |
            docker build -t stanja/manual-builder:latest .
      - run:
          name: Push to DockerHub
          command: |
            docker push stanja/manual-builder:latest
